version: '3.8'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
     - "5557:5557"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locust/locust_files/locustfile.py --master -H http://django:8000 --config /mnt/locust/locust/locust.conf

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locust/locust_files/locustfile.py --worker --master-host master
