# Generated by Django 5.0.6 on 2024-05-25 19:04

import django.db.models.deletion
import ePubColab.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epub",
                    models.FileField(
                        storage=ePubColab.storage.ePubStorage,
                        upload_to="Users/neeraj_py/Desktop/epubReader/media/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("epub", "user")},
            },
        ),
    ]
