# Generated by Django 5.0.6 on 2024-05-25 19:21

import ePubColab.models
import ePubColab.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ePubColab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="epub",
            field=models.FileField(
                storage=ePubColab.storage.ePubStorage,
                upload_to=ePubColab.models.user_directory_path,
            ),
        ),
    ]
