# Generated by Django 5.0.6 on 2024-05-26 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ePubColab", "0002_alter_book_epub"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(default="LIVE", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("epub", "user", "status")},
        ),
    ]
