# Generated by Django 5.0.6 on 2024-05-26 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ePubColab", "0003_alter_book_unique_together_book_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("epub", "user")},
        ),
    ]
