# Generated by Django 5.0.6 on 2024-05-27 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ePubColab", "0006_sharedbook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedbook",
            old_name="shared_with",
            new_name="shared",
        ),
        migrations.AlterUniqueTogether(
            name="sharedbook",
            unique_together={("epub", "shared", "user")},
        ),
    ]
