# Generated by Django 5.0.6 on 2024-05-27 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ePubColab", "0007_rename_shared_with_sharedbook_shared_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedbook",
            old_name="shared",
            new_name="shared_with",
        ),
        migrations.AlterUniqueTogether(
            name="sharedbook",
            unique_together={("epub", "shared_with", "user")},
        ),
    ]
